### ISSUE TITLE
Set Time limit for Hard and Very Questions[FEATURE] 

### ISSUE THREAD

**Issue by SasiVardhan247** [prakhartiwari0/Arito#106]
**Is your feature request related to a problem? Please describe.**
The game would be interesting if we add a timer to hard problems. It will create some tension which helps in time management and getting habituated to competitive exams.

**Describe the solution you'd like**
I want to add a certain time limit set to questions on hard and very hard levels. When the timer goes to 0 then the user will be going to the next question.

**Describe alternatives you've considered**
An Alternative is if the user doesn't complete the question in a given time he will be awarded 0 marks for that question.

**Additional context**

**Comment by prakhartiwari0** [comment]
This app is not targeted for competitive exams, it's mainly for kids who simply want to practice their arithmetic skills. That feature is a good-to-have but for now, it's not required. Maybe in future if get some feature requests like this, we can then consider it. 
Also, there's a time duration given in the result that the person took to complete the whole test, so they can focus on reducing that time duration gradually with the same number of questions and difficulty level, which is basically the same thing. 

I hope I was able to explain this @SasiVardhan247. From now, if you get an idea for feature, kindly write about it in the discussions so that we can discuss about it, rather than raising a new issue for it.

Happy Contributing!
