### ISSUE TITLE
create a sign up page

### ISSUE THREAD

**Issue by silwite** [prakhartiwari0/Arito#108]
hello, Please assign this to me as a contributor under GSSOC'23. Tech Stack- MERN stack

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me.
@prakhartiwari0

**Comment by prakhartiwari0** [comment]
A SignUp Page is NOT REQUIRED for this project. It's for kids and they don't have so much knowledge about tech, and they don't care. We need to make this app for them and not expect features just because other apps have it, understand the nature of this project and then you will be able to contribute genuinely.

@silwite @PatilHarshh 
I would recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
