### ISSUE TITLE
Timer feature, authenticatication, Fix some UI/UX issues, Create contact us page

### ISSUE THREAD

**Issue by arnab-sur** [prakhartiwari0/Arito#116]
**Is your feature request related to a problem? Please describe.**
1. There is not any timer feature showing the time elapsed during test all the time. It's just shown after submitting the test.
2. No option to resume or exit the test.
3. The UI/UX should have been more better.
4. In Reviews and Reactions there should be many other sign up options other than github only, like google or facebook or rather an individual signup/signin form.

**Describe the solution you'd like** or **Describe alternatives you've considered**
1. Adding total time elapsed during the test or set a fixed time for each question to be solved within, depending on their level of difficulty.
2.  Adding option to Resume the test (timer also be resumed) or Exit the test and back to homepage.
3.  The fonts, colour combinations used in this web app can be changed to a beautiful palette to look more impressive.
4.  Adding authentication feature by creating Arito's own authentication system ( signin/signup form) , or use google or facebook signin as most of the common user of this web app may noy have github accounts.
5. For improvement we can create a contact us section where user can contact us, they can send us some problems created by them, and after verifying we can add more math problems to our web app. 

**Additional context**
6. To make it a big one, we have to create a backend for this web app where we can store authenticated user's each test scores and analyze if their math skills are improved from the previous one or not and help them to more work upon that specific part where they do errors.

** Hope the project admin assigns me this to help me contributing to this project. Thank You :)

**Comment by prakhartiwari0** [comment]
Hello @arnab-sur,  it's good to see you want to contribute to the project.
However, I want to point out that this is not a good practice to include so many problems in one issue. Please raise specific issues and describe the details of each and every one of them. Explain the reason behind each one too. Also, you must check the existing issues because there are many of them trying to solve the specific problems you mentioned here.

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
