### ISSUE TITLE
[FEATURE]  Add Equation Questions (Finding x)

### ISSUE THREAD

**Issue by AlfiyaSiddique** [prakhartiwari0/Arito#224]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I want to add one more type of question, where we provide equation questions. All the equations will be linear equations and the user have to find the value of x. The user has to give answer in mcqs. 

## Request 
If you find this feature worth implementing then please assign me under gssoc23 label.

**Comment by gambhirsharma** [comment]
@AlfiyaSiddique for making such type of Feature we need to have a discussion with the other contributor as well so that it matches the agenda of this project. You can open a new discussion where we can discuss this. Something similar to #6 

For now, I am temporarily closing this issue. You can reopen this issue after having a discussion with another contributor in the discussion section.
