### ISSUE TITLE
[BUG] Unable to send answers past a certain length

### ISSUE THREAD

**Issue by nathenialalleyne** [prakhartiwari0/Arito#35]
**Describe the bug**
If you attempt to send in an answer that overflows the text box the answer button does nothing

**To Reproduce**
1. Create a quiz 
2. Attempt to answer a question but fill the textbox so it begins to overflow

**Expected behavior**
Either the answer should be put through or there should be some type of indication that the length of you answer exceeds the maximum

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107.0.5304.107

**Comment by prakhartiwari0** [comment]
@nateachino I would recommend adding screenshots also! That will help others to understand the problem better and easily.

**Comment by prakhartiwari0** [comment]
@nateachino Actually it is done on purpose, here is the js code that is doing that -https://github.com/prakhartiwari0/Arito/blob/main/js/main.js#L147

The logic is, the biggest answer which possibly can come in the whole test is the product of **99,999 x 99,999** because they are the **biggest number that can be generated by the code** in case the user selects **very hard** in the difficult level. And we all know that the product of any two numbers will always be greater than their difference, sum, quotient, or remainder.
And therefore, if the user tries to put numbers unnecessarily too big, it doesn't let them submit it.

I hope I was able to explain, please ask if you have any more queries!
