### ISSUE TITLE
[FEATURE]  Add home button

### ISSUE THREAD

**Issue by lewisushindi** [prakhartiwari0/Arito#57]
users can't go back to the main page after they have done testing themselves and results displayed.

**Comment by prakhartiwari0** [comment]
Hey @lewisushindi, I am sorry but this is not a good way of contributing to an open-source project. You should check if there are any existing issues. There is already an issue with this, check  #27

**Comment by lewisushindi** [comment]
thats the Restart button
![Screenshot (87)](https://user-images.githubusercontent.com/104835999/210729483-0d4946cb-42b3-446c-967e-18f77df2b566.png)

am Talking about a button that can allow one to go back to the page below
![Screenshot (88)](https://user-images.githubusercontent.com/104835999/210729869-dd34563a-362a-4b9e-b328-046ea0b4575f.png)

**Comment by prakhartiwari0** [comment]
Oh yeah @lewisushindi, that could be a good feature. I got confused as you referred to the `main page` as there is a main.html file that already exists and the issue was targeting to add buttons to redirect the user to the Main Form, which is inside that main.html file only.

But you should properly describe your issue by filling up the issue template, please open a new issue with a proper & accurate description of what you want and why you want that. The templates are there for a reason! they are to help you with that.

 Happy Contributing!

**Comment by lewisushindi** [comment]
@prakhartiwari0  Thank you sir! Point gotten...Doing that in a few.
